# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'url_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.short_url_button = QtWidgets.QPushButton(self.centralwidget)
        self.short_url_button.setGeometry(QtCore.QRect(10, 460, 771, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.short_url_button.setFont(font)
        self.short_url_button.setObjectName("short_url_button")
        self.short_url_button.setStyleSheet("background-color: #4F86F7")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 170, 771, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.enter_url_label = QtWidgets.QLabel(self.groupBox)
        self.enter_url_label.setGeometry(QtCore.QRect(40, 70, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enter_url_label.setFont(font)
        self.enter_url_label.setObjectName("enter_url_label")
        self.output_label = QtWidgets.QLabel(self.groupBox)
        self.output_label.setGeometry(QtCore.QRect(40, 190, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.url_input_text = QtWidgets.QLineEdit(self.groupBox)
        self.url_input_text.setGeometry(QtCore.QRect(280, 70, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.url_input_text.setFont(font)
        self.url_input_text.setText("")
        self.url_input_text.setObjectName("url_input_text")
        self.short_url_output = QtWidgets.QLineEdit(self.groupBox)
        self.short_url_output.setGeometry(QtCore.QRect(280, 200, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.short_url_output.setFont(font)
        self.short_url_output.setText("")
        self.short_url_output.setObjectName("short_url_output")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 771, 111))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setIndent(190)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.short_url_button.setText(_translate("MainWindow", "Shortening URL"))
        self.enter_url_label.setText(_translate("MainWindow", "Enter URL"))
        self.output_label.setText(_translate("MainWindow", "Output"))
        self.label.setText(_translate("MainWindow", "Short That URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
